import { createClient } from "@/utils/supabase/server"
import { notFound } from "next/navigation"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

export const revalidate = 0

export default async function BrandEditorPage({
  params,
}: {
  params: { brandSlug: string }
}) {
  const supabase = createClient()
  const { data: brand } = await supabase.from("brands").select("name").eq("slug", params.brandSlug).single()

  if (!brand) {
    notFound()
  }

  const budibaseUrl = process.env.NEXT_PUBLIC_BUDIBASE_URL

  if (!budibaseUrl) {
    return (
      <div className="flex items-center justify-center min-h-screen bg-gray-50">
        <Card className="w-full max-w-lg mx-4">
          <CardHeader>
            <CardTitle className="text-2xl text-red-600">Configuration Error</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-gray-700">
              The Budibase URL is not configured. Please set the{" "}
              <code className="px-1 py-0.5 font-mono text-sm bg-gray-200 rounded">NEXT_PUBLIC_BUDIBASE_URL</code>{" "}
              environment variable in your project settings.
            </p>
          </CardContent>
        </Card>
      </div>
    )
  }

  // The autogenerated admin screens in Budibase are typically located at a base URL.
  // You may need to adjust this to point to the specific entry point of your admin app.
  const editorUrl = budibaseUrl

  return (
    <iframe src={editorUrl} className="w-full h-full border-0" title={`${brand.name} Form Editor`} allowFullScreen />
  )
}
