-- This script configures the primary key columns to auto-increment,
-- which is the standard and correct way to generate new IDs.
-- This will resolve the "violates not-null constraint" error during inserts.

-- Set 'id' in the 'sections' table to be a modern, auto-incrementing identity column.
ALTER TABLE "public"."sections" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;

-- Do the same for the 'items' table.
ALTER TABLE "public"."items" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;

-- And for the 'options' table to be safe.
ALTER TABLE "public"."options" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;

-- And for the 'uploaded_files' table as well.
ALTER TABLE "public"."uploaded_files" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;


-- After running this script, your database will correctly handle ID generation,
-- and the "Save Changes" functionality in the form editor will work as expected.
