-- This script fixes the primary key columns to ensure they auto-increment.
-- This resolves "violates not-null constraint" errors on insert.

-- Fix for the 'sections' table
ALTER TABLE "public"."sections" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;

-- Fix for the 'items' table
ALTER TABLE "public"."items" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;

-- Fix for the 'options' table
ALTER TABLE "public"."options" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;

-- Note: If the above commands fail because a default is already set,
-- you may need to drop the old default first, e.g.:
-- ALTER TABLE "public"."sections" ALTER COLUMN "id" DROP DEFAULT;
-- Then re-run the ADD GENERATED command.
